### ISSUE TITLE
Common part on wson-tp-attributes and otn-tp-attributes

### ISSUE THREAD

**Issue by haomianzheng** [ietf-ccamp-wg/draft-ietf-ccamp-wson-yang#2]
This issue is proposed in https://mailarchive.ietf.org/arch/msg/ccamp/dURl9mDv5ObaH2v7eo5lckjG1tw/. 

3) The wson-tp-attributes grouping covers similar capabilities as the otn-tp-attributes grouping in draft-ietf-ccamp-otn-topo-yang-10

It is proposed to rename and move the otn-tp-attributes grouping to the layer1-types module and to re-use it in both the wson-topology and otn-topology modules

     augment /nw:networks/nw:network/nw:node
               /nt:termination-point/tet:te:
       +--rw supported-payload-types* [index]
       |  +--rw index           uint16
       |  +--rw payload-type?   string
       +--rw client-facing?             boolean

   
grouping wson-tp-attributes {
     description "wson-tp-attributes";

     list supported-payload-types {
       key "index";
       description
         "Supported payload types of a TP (Termination Point).
          The payload type is defined as the generalized PIDs
          (Payload Identifiers) in GMPLS";
       leaf index {
         type uint16;
         description "payload type index";
       }
       leaf payload-type {
         type string;
         description "the payload type supported by this client TP";
         reference
           "http://www.iana.org/assignments/gmpls-sig-parameters
            /gmpls-sig-parameters.xhtml";
       }
     }
     leaf client-facing {
       type boolean;
       default 'false';
       description
         "Indicates if it is a client-facing TP";
     }
   }

**Comment by italobusi** [comment]
Addressed in https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-wson-yang/pull/3/commits/216c09122bb69cb477f83776a141c7be0a87a293

The attributes have been removed since they are already present in the otn-topology
